export const projects = [
  {
    id: 'askmydocs',
    name: 'AskMyDocs',
    tag: 'RAG · Document Intelligence',
    blurb: 'A section-aware RAG chatbot that answers questions over uploaded documents, built to survive real production edge cases — not just a demo.',
    detail: 'Rewrote chunking from raw character slicing to section-aware splitting, taking chunk match confidence from 29% to 62%. Layered in hybrid search (RRF), asymmetric embedding fixes, and conversation memory, then hardened it with Zod validation, a repository layer, and Vitest coverage.',
    caseStudy: `Chunking was naive — raw character slicing let chunk boundaries fall mid-sentence or mid-word, and a hard 512-char embedding cap silently truncated the back half of every ~800-char chunk. Rewrote chunking to be sentence-aware with word-boundary-safe overlap, and fixed the embedding call to cover full chunks — retrieval relevance jumped immediately.

Then found a second, subtler bug: queries were being embedded with Cohere's search_document type instead of search_query — silently degrading every single retrieval, even though the chunk embeddings themselves were correct. Cohere's embeddings are asymmetric by design; using the wrong input type is invisible until you actually measure retrieval quality.

Built an LLM-as-judge eval harness to catch regressions automatically — then found a bug in the judge itself: it was scoring answers against a shorter context slice than the answer model actually saw, falsely penalizing correct answers as unsupported. Fixed the judge, then hit a third issue — the reasoning model was silently returning empty answers on hard questions because max_tokens didn't account for internal reasoning tokens, with no error thrown. Caught only via structured logging of finish_reason.`,
    stack: ['Next.js', 'Supabase', 'pgvector', 'Groq'],
    metric: { value: '80%', label: 'eval pass rate' },
    links: { github: 'https://github.com/ayush-s-tomar/intellect-docs-ai', demo: 'https://intellect-docs-ai.vercel.app/' },
    status: 'live',
  },
  {
    id: 'salesagent',
    name: 'SalesAgent',
    tag: 'LangGraph · B2B Automation',
    blurb: 'Paste a LinkedIn URL — the agent researches the lead, scores them with a trained ML model, drafts a personalized cold email, and pushes it into a CRM pipeline.',
    detail: 'A LangGraph agent chained to a Random Forest scoring model and Tavily search for live research, with SQLite-backed memory so the pipeline remembers every lead it has touched.',
    stack: ['LangGraph', 'FastAPI', 'React', 'scikit-learn', 'Groq'],
    metric: { value: '4', label: 'stage pipeline' },
    links: { github: 'https://github.com/ayush-s-tomar/salesagent', demo: 'https://salesagent-theta.vercel.app/' },
    status: 'live',
  },
  {
    id: 'resumeiq',
    name: 'Resume Screener — LoRA',
    tag: 'LoRA · Fine-Tuned Screening',
    blurb: 'A LoRA fine-tuned Qwen2.5-0.5B model that returns structured JSON resume screening verdicts — outperforms prompting alone on output consistency.',
    detail: 'Fine-tuned rather than prompted, so the model reliably returns valid structured JSON verdicts instead of drifting formats across resumes — a real fix for a production reliability problem, not a demo trick.',
    caseStudy: `Benchmarked the LoRA-adapted model against the same base Qwen2.5-0.5B running zero-shot, across the full 96-example eval set. Both hit 100% valid JSON — prompting alone is enough to get the format right. The gap shows up in whether the verdict is actually correct: zero-shot verdict accuracy was 17.7%, fine-tuned hit 88.5%. Mean absolute error on the ATS score dropped from 32.03 points to 5.39. Fine-tuning didn't fix formatting — it fixed judgment.`,
    stack: ['Qwen2.5-0.5B', 'LoRA', 'Flask', 'Docker'],
    metric: { value: '88.5%', label: 'verdict accuracy' },
    links: { github: 'https://github.com/ayush-s-tomar/resume-screener-lora', demo: 'https://resume-screener-finetune.onrender.com/' },
    status: 'live',
  },
  {
    id: 'agentloop',
    name: 'AgentLoop',
    tag: 'LangGraph · Research Agent',
    blurb: 'A multi-step research agent that plans, searches, reflects, and writes sourced reports, streaming its own reasoning back to you in real time, like watching a CI job run.',
    detail: 'SSE streaming plus SQLite long-term memory let the agent pick up context across sessions. The UI went through four design passes before landing on a GitHub Actions-style live log, because that\'s the mental model that actually fit an agent\'s execution trace.',
    stack: ['LangGraph', 'FastAPI', 'SQLite', 'SSE'],
    metric: { value: '6', label: 'graph nodes' },
    links: { github: 'https://github.com/ayush-s-tomar/agentloop', demo: 'https://agentloop.onrender.com/' },
    status: 'secondary',
  },
  {
    id: 'startupscope',
    name: 'StartupScope',
    tag: 'CrewAI · Multi-Agent',
    blurb: 'A crew of specialized agents that research a company from scratch and hand back structured competitive intelligence.',
    detail: 'Each agent owns one job — sourcing, summarizing, or scoring — coordinated by CrewAI into a single written startup report.',
    stack: ['CrewAI', 'Python', 'Groq'],
    metric: { value: 'multi', label: 'agent crew' },
    links: { github: 'https://github.com/ayush-s-tomar/startupscope', demo: 'https://startupscope-q76d.onrender.com/' },
    status: 'secondary',
  },
  {
    id: 'mcp-server',
    name: 'Portfolio MCP Server',
    tag: 'MCP · Tooling',
    blurb: 'An MCP server that turns this portfolio into queryable tools — no more scrolling a README to find what I\'ve built.',
    detail: 'A hands-on exploration of the Model Context Protocol, built as an extension of the portfolio itself, exposing project data as tools any MCP-compatible client can query directly.',
    stack: ['MCP', 'Python'],
    metric: { value: 'MCP', label: 'protocol native' },
    links: { github: 'https://github.com/ayush-s-tomar/portfolio-mcp-server', demo: '#' },
    status: 'secondary',
  },
];

export const skills = {
  'agents & orchestration': ['LangGraph', 'CrewAI', 'Multi-agent design', 'MCP'],
  'models & inference': ['Groq / LLaMA', 'RAG pipelines', 'LoRA fine-tuning', 'Prompt engineering'],
  'backend': ['FastAPI', 'Flask', 'Python', 'REST APIs'],
  'frontend': ['React', 'Vite', 'Streamlit'],
  'data & infra': ['Supabase', 'pgvector', 'SQLite', 'Docker'],
  'deploy': ['Render', 'Vercel', 'Streamlit Cloud', 'GitHub Actions'],
};